# Generated by Django 4.2 on 2023-11-28 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_alter_aluno_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Data_pagamento',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 18, 35, 50, 283663, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
